### ISSUE TITLE
SecurityException when passing the integration tests in native mode

### ISSUE THREAD

**Issue by agoncal** [quarkiverse/quarkus-azure-services#20]
When executing a `mvn integration-test -Dnative` command, the following exception is thrown:

```
Caused by: java.lang.SecurityException: class "com.azure.storage.blob.BlobServiceClient"'s signer information does not match signer information of other classes in the same package
```

The class `BlobServiceClient` is in the artifact called `com.azure:azure-storage-blob`. This artifact is used by `io.quarkiverse.azureservices:quarkus-azure-storage-blob` which is in turned used by `io.quarkiverse.azureservices:quarkus-azure-storage-blob-deployment`.

I tried verifying JARs with the following Maven plugin:

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-jarsigner-plugin</artifactId>
    <version>3.0.0</version>
    <executions>
        <execution>
            <id>verify</id>
            <goals>
                <goal>verify</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <verbose>true</verbose>
        <certs>true</certs>
    </configuration>
</plugin>
```

Looking at the `azure-storage-blob-12.20.0.jar` inside the file `META-INF/MANIFEST.MF` we see:

```
Name: com/azure/storage/blob/BlobServiceClientBuilder.class
SHA-256-Digest: vknX58uqQ616EHc/doYs/7fte00cZfMdDjyNo4U8gF4=
```

When using Jarsigner we can see that the JAR is verified:

```
$ jarsigner -verify azure-storage-blob-12.20.0.jar

jar verified.
```

### Full Stack Trace with Java 11

```
$ java -version
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 11.0.17+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 11.0.17+8-jvmci-22.3-b08, mixed mode)



[1/7] Initializing... 
 Version info: 'GraalVM 22.3.0 Java 11 CE'
 Java version info: '11.0.17+8-jvmci-22.3-b08'
 C compiler: cc (apple, arm64, 14.0.0)
 Garbage collector: Serial GC
 3 user-specific feature(s)
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase for the [org.jboss.threads] categories
 - io.quarkus.runtime.graal.ResourcesFeature: Register each line in META-INF/quarkus-native-resources.txt as a resource on Substrate VM
[2/7] Performing analysis...  [WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/Users/agoncal/Documents/Code/Quarkiverse/quarkus-azure-services/integration-tests/target/quarkus-azure-services-integration-tests-999-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-common-4.1.82.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
16:42:46,792 INFO  [com.azu.cor.imp.jac.JacksonVersion] Package versions: jackson-core=2.13.4, jackson-databind=2.13.4-2, jackson-dataformat-xml=2.13.4, jackson-datatype-jsr310=2.13.4, azure-core=1.33.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
]                                                                         (5.2s @ 1.24GB)
   5,006 (82.00%) of  6,105 classes reachable
   6,827 (64.24%) of 10,627 fields reachable
  18,204 (53.34%) of 34,128 methods reachable
     553 classes, 1,423 fields, and 1,163 methods registered for reflection
       1 native library: -framework CoreServices

Fatal error: com.oracle.svm.hosted.annotation.AnnotationMetadata$AnnotationExtractionError: java.lang.reflect.InvocationTargetException
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.annotation.SubstrateAnnotationExtracter.getRoot(SubstrateAnnotationExtracter.java:460)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.annotation.SubstrateAnnotationExtracter.getAnnotationData(SubstrateAnnotationExtracter.java:195)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.annotation.SubstrateAnnotationExtracter.extractAnnotation(SubstrateAnnotationExtracter.java:166)
        at org.graalvm.nativeimage.base/com.oracle.svm.util.GuardedAnnotationAccess.getAnnotation(GuardedAnnotationAccess.java:82)
        at org.graalvm.nativeimage.base/com.oracle.svm.util.GuardedAnnotationAccess.getAnnotation(GuardedAnnotationAccess.java:74)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.SVMHost.platformSupported(SVMHost.java:740)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:461)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.getDeclaredMethods(AnalysisType.java:1194)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.findMethod(AnalysisType.java:1199)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionDataBuilder.registerHidingSubTypeMethods(ReflectionDataBuilder.java:376)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionDataBuilder.registerHidingSubTypeMethods(ReflectionDataBuilder.java:396)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionDataBuilder.processMethodMetadata(ReflectionDataBuilder.java:279)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionDataBuilder.duringAnalysis(ReflectionDataBuilder.java:199)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionFeature.duringAnalysis(ReflectionFeature.java:254)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:748)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:748)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:162)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:745)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.annotation.SubstrateAnnotationExtracter.getRoot(SubstrateAnnotationExtracter.java:440)
        ... 23 more
Caused by: java.lang.SecurityException: class "com.azure.storage.blob.BlobServiceClient"'s signer information does not match signer information of other classes in the same package
        at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1151)
        at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:906)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1015)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at jdk.internal.vm.ci/jdk.vm.ci.hotspot.CompilerToVM.asReflectionExecutable(Native Method)
        at jdk.internal.vm.ci/jdk.vm.ci.hotspot.CompilerToVM.asReflectionExecutable(CompilerToVM.java:1126)
        at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJDKReflection.getMethod(HotSpotJDKReflection.java:291)
        ... 27 more
```

### Full Stack Trace with Java 17

```
$ java -version
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)


[1/7] Initializing... 
 Version info: 'GraalVM 22.2.0 Java 17 CE'
 Java version info: '17.0.4+8-jvmci-22.2-b06'
 C compiler: cc (apple, arm64, 14.0.0)
 Garbage collector: Serial GC
 3 user-specific feature(s)
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase for the [org.jboss.threads] categories
 - io.quarkus.runtime.graal.ResourcesFeature: Register each line in META-INF/quarkus-native-resources.txt as a resource on Substrate VM
[2/7] Performing analysis...  [16:31:03,513 INFO  [com.azu.cor.imp.jac.JacksonVersion] Package versions: jackson-core=2.13.4, jackson-databind=2.13.4-2, jackson-dataformat-xml=2.13.4, jackson-datatype-jsr310=2.13.4, azure-core=1.33.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
*]                                                                        (4.9s @ 1.10GB)
   5,090 (83.25%) of  6,114 classes reachable
   6,894 (61.83%) of 11,150 fields reachable
  18,450 (58.96%) of 31,295 methods reachable
     569 classes, 1,424 fields, and   342 methods registered for reflection
       1 native library: -framework CoreServices

Fatal error: com.oracle.svm.hosted.annotation.AnnotationMetadata$AnnotationExtractionError: java.lang.reflect.InvocationTargetException
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.annotation.SubstrateAnnotationExtracter.getRoot(SubstrateAnnotationExtracter.java:454)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.annotation.SubstrateAnnotationExtracter.getAnnotationData(SubstrateAnnotationExtracter.java:189)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.annotation.SubstrateAnnotationExtracter.extractAnnotation(SubstrateAnnotationExtracter.java:166)
        at org.graalvm.nativeimage.base/com.oracle.svm.util.GuardedAnnotationAccess.getAnnotation(GuardedAnnotationAccess.java:81)
        at org.graalvm.nativeimage.base/com.oracle.svm.util.GuardedAnnotationAccess.getAnnotation(GuardedAnnotationAccess.java:73)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.SVMHost.platformSupported(SVMHost.java:721)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:449)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.getDeclaredMethods(AnalysisType.java:1158)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.findMethod(AnalysisType.java:1163)
        at org.graalvm.nativeimage.builder/com.oracle.svm.reflect.hosted.ReflectionDataBuilder.registerHidingSubTypeMethods(ReflectionDataBuilder.java:386)
        at org.graalvm.nativeimage.builder/com.oracle.svm.reflect.hosted.ReflectionDataBuilder.registerHidingSubTypeMethods(ReflectionDataBuilder.java:406)
        at org.graalvm.nativeimage.builder/com.oracle.svm.reflect.hosted.ReflectionDataBuilder.processMethodMetadata(ReflectionDataBuilder.java:287)
        at org.graalvm.nativeimage.builder/com.oracle.svm.reflect.hosted.ReflectionDataBuilder.duringAnalysis(ReflectionDataBuilder.java:187)
        at org.graalvm.nativeimage.builder/com.oracle.svm.reflect.hosted.ReflectionFeature.duringAnalysis(ReflectionFeature.java:238)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:734)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:78)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:734)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.runAnalysis(PointsToAnalysis.java:755)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:731)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:564)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.annotation.SubstrateAnnotationExtracter.getRoot(SubstrateAnnotationExtracter.java:434)
        ... 23 more
Caused by: java.lang.SecurityException: class "com.azure.storage.blob.BlobServiceClient"'s signer information does not match signer information of other classes in the same package
        at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1158)
        at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:902)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at jdk.internal.vm.ci/jdk.vm.ci.hotspot.CompilerToVM.asReflectionExecutable(Native Method)
        at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJDKReflection.getMethod(HotSpotJDKReflection.java:291)
        ... 27 more

```

### References

* https://github.com/quarkusio/quarkus/issues/13146

**Comment by agoncal** [comment]
Looking at @ppalaga [comment](https://github.com/quarkusio/quarkus/issues/13146#issuecomment-791411350), I removed the `@ApplicationScoped` annotation on `StorageBlobServiceClientProducer::blobServiceClient` and it didn't fail anymore. But other issues in building native:

```
    @Produces
    @ApplicationScoped
    public BlobServiceClient blobServiceClient() {
        return new BlobServiceClientBuilder().connectionString(storageBlobConfiguration.connectionString).buildClient();
    }
```

**Comment by ppalaga** [comment]
@agoncal here is a sketch how it could work: https://github.com/quarkiverse/quarkus-azure-services/pull/24

**Comment by agoncal** [comment]
Fixed by https://github.com/quarkiverse/quarkus-azure-services/pull/24
