### ISSUE TITLE
Build is failing XMLInputFactory cannot be found

### ISSUE THREAD

**Issue by agoncal** [quarkiverse/quarkus-azure-services#36]
The code that is making the native compilation fail is:

```java
void shouldDownloadATextfile() {
    given()
            .when().get("/quarkus-azure-storage-blob")
            .then()
            .statusCode(200)
            .body(startsWith("Hello quarkus-azure-storage-blob"));
}
```

It has been disabled for now. It invokes the following method:

```java
@GET
@Produces(MediaType.TEXT_PLAIN)
public String downloadBlob() {
    BlobContainerClient blobContainerClient = blobServiceClient
            .createBlobContainerIfNotExists("container-quarkus-azure-storage-blob");
    BlobClient blobClient = blobContainerClient.getBlobClient("quarkus-azure-storage-blob.txt");

    return blobClient.downloadContent().toString();
}
```

This returns plain text and should not need any XML parser (as shown in the stack trace below)

```java
2022-11-18 11:21:48,260 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /quarkus-azure-storage-blob failed, error id: a2fcf69d-510a-43ee-b2af-637943bf67d0-1: org.jboss.resteasy.spi.UnhandledException: reactor.core.Exceptions$ReactiveException: javax.xml.stream.FactoryConfigurationError: Provider for javax.xml.stream.XMLInputFactory cannot be found
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:105)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:359)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: reactor.core.Exceptions$ReactiveException: javax.xml.stream.FactoryConfigurationError: Provider for javax.xml.stream.XMLInputFactory cannot be found
```

# References

* https://stackoverflow.com/questions/72953084/quarkus-native-mode-provider-for-javax-xml-stream-xmlinputfactory-cannot-be-fo

**Comment by ppalaga** [comment]
My understanding is that this is caused by the fact that Azure Service clients use XML over HTTP internally. I have sent a fix https://github.com/quarkiverse/quarkus-azure-services/pull/38
